import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Link from 'next/link';
import ConsentBanner from '@/components/ConsentBanner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="text-center text-lg-start mt-auto py-3" style={{ backgroundColor: 'var(--color-background-medium)', color: 'var(--color-text-light)' }}>
          <div className="container p-4">
            <section className="mb-4">
              <Link href="/legal/privacy" className="text-light me-4">Privacy Policy</Link>
              <Link href="/legal/terms" className="text-light me-4">Termini di Servizio</Link>
              <Link href="/legal/cookies" className="text-light">Cookie Policy</Link>
            </section>
          </div>
          <div className="text-center p-3" style={{ backgroundColor: 'var(--color-background-dark)' }}>
            © 2025 TastieriniKD
          </div>
        </footer>
        <ConsentBanner />
      </body>
    </html>
  );
}
